version: '3'

services:
  app:
    build: .
    volumes:
      - ".:/var/myapp"
    environment:
      - "TZ=Asia/Tokyo"
      - "ODDSPARK_USER_ID=user_id"
      - "ODDSPARK_PASSWORD=password"
      - "ODDSPARK_PIN=pin"
    depends_on:
      - "selenium-hub"

  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 15900:5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - "selenium-hub"
    environment:
      - "HUB_HOST=selenium-hub"
      - "HUB_PORT=4444"

  selenium-hub:
    image: selenium/hub
    ports:
      - 14444:4444
