app:
  build: .
  container_name: "app"
  volumes:
    - ".:/var/myapp"
  environment:
    - "TZ=Asia/Tokyo"
  links:
    - selenium-hub:hub

chrome:
  image: selenium/node-chrome-debug
  container_name: "chrome"
  ports:
    - 5900:5900
  volumes:
    - /dev/shm:/dev/shm
  links:
    - selenium-hub:hub

selenium-hub:
  image: selenium/hub
  container_name: "selenium-hub"
  ports:
    - 4444:4444
