version: '3'

services:
  app:
    build: .
    volumes:
      - ".:/var/myapp"
    environment:
      - "TZ=Asia/Tokyo"
      - "ODDSPARK_USER_ID=${ODDSPARK_USER_ID}"
      - "ODDSPARK_PASSWORD=${ODDSPARK_PASSWORD}"
      - "ODDSPARK_PIN=${ODDSPARK_PIN}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "API_PREDICT_URL=${API_PREDICT_URL}"
      - "API_PREDICT_AUTH_USER=${API_PREDICT_AUTH_USER}"
      - "API_PREDICT_AUTH_PASSWORD=${API_PREDICT_AUTH_PASSWORD}"
    ports:
      - 5000:5000
    depends_on:
      - "selenium-hub"
      - "db"

  db:
    image: postgres:12
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"

  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 15900:5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - "selenium-hub"
    environment:
      - "HUB_HOST=selenium-hub"
      - "HUB_PORT=4444"

  selenium-hub:
    image: selenium/hub
    ports:
      - 14444:4444
