version: '3'

services:
  app:
    build: .
    links:
      - selenium-hub:hub
    volumes:
      - ".:/var/myapp"
    environment:
      - "TZ=Asia/Tokyo"
  selenium-hub:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome-debug
    links:
      - selenium-hub:hub
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
